<div class="discount troopid-connect">
    <h2><?php echo $this->__("Military Discounts with Troop ID") ?></h2>
    <?php if ($this->hasAffiliation()): ?>
        <div class="affiliation">
            <?php echo $this->__("You have verified yourself as") . " <strong>" . $this->getAffiliation() . "</strong>" ?>
        </div>
    <?php else: ?>
        <div class="button">
            <a href="javascript:void(0);" id="troopid-connect-trigger" title="<?php echo $this->__("Verify your military affiliation with Troop ID") ?>">
                <img alt="<?php echo $this->__("Verify your military affiliation with Troop ID") ?>" src="https://s3.amazonaws.com/troopid/buttons/verify-button-red-235x40.png" />
            </a>
        </div>
    <?php endif ?>
    <div class="about">
        <a href="javascript:void(0);" id="troopid-modal-trigger"><?php echo $this->__("What is this?") ?></a>
    </div>

    <div id="troopid-modal" style="display: none;"></div>
    <div id="troopid-modal-content" style="display: none;">
        <h3><?php echo $this->__("What is Troop ID?") ?></h3>
        <a href="javascript:void(0);" class="close" id="troopid-modal-closer">[x]</a>
        <?php echo $this->getAbout() ?>
    </div>
</div>